
#Database configuration
development:
  adapter: postgresql
  encoding: unicode
  database: dspace
  username: dspace
  host: localhost
  password: dspace # if you need a password

test:
  adapter: postgresql
  encoding: unicode
  database: dspace
  username: dspace
  host: localhost
  password: dspace # if you need a password

production:
  adapter: postgresql
  encoding: unicode
  database: dspace
  username: dspace
  host: localhost
  password: dspace # probably you will need a password
