version: "2"
services:
  localhost:
    hostname: 'postgres'
    restart: always
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data

  dspace:
    image: unixelias/docker-dspace:6.0.1-alpha
    ports:
      - 8080:8080
    depends_on:
      - localhost
    environment:
      - POSTGRES_DB_HOST=postgres
      - POSTGRES_ADMIN_USER=postgres
      - POSTGRES_ADMIN_PASSWORD=admin
      - POSTGRES_SCHEMA=dspace
      - POSTGRES_USER=dspace
      - POSTGRES_PASSWORD=password
    command: start-dspace

volumes:
  db_data:
