version: "2"
services:
  postgres:
    image: unixelias/postgres-dspace:9.6-alpha
    hostname: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  dspace:
    image: unixelias/docker-dspace:6.0-alpha
    ports:
      - 8080:8080
    depends_on:
      - localhost
    environment:
      - POSTGRES_DB_HOST=localhost  
      - POSTGRES_ADMIN_USER=postgres
      - POSTGRES_ADMIN_PASSWORD=admin
      - POSTGRES_SCHEMA=dspace
      - POSTGRES_USER=dspace
      - POSTGRES_PASSWORD=password
    command: start-dspace

volumes:
  db_data:
